import { useState } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import { useMutation, useQuery } from "@tanstack/react-query";
import { motion } from "framer-motion";
import { ArrowLeft, MapPin, Sparkles, Send, Wand2 } from "lucide-react";
import { toast } from "sonner";
import { AppShell } from "@/components/app/AppShell";
import { appsApi } from "@/lib/mock-api";

export default function ApplyJob() {
  const { id = "job_1" } = useParams();
  const navigate = useNavigate();
  const [cover, setCover] = useState("");

  const { data: job } = useQuery({ queryKey: ["job", id], queryFn: () => appsApi.getJob(id) });

  const apply = useMutation({
    mutationFn: () => appsApi.apply({ jobId: id, coverLetter: cover }),
    onSuccess: () => {
      toast.success("Application submitted", { description: "Tracking it on your dashboard." });
      navigate("/applications");
    },
  });

  const draftWithAI = () => {
    if (!job) return;
    setCover(
      `Hi ${job.startup.name} team,\n\nYour ${job.title} role lines up tightly with my recent work — especially across ${job.techStack.slice(0, 3).join(", ")}. I've shipped production systems at similar scale and would love to bring that to your team.\n\nHappy to share specifics on a quick call.\n\n— Aria`,
    );
    toast("Draft generated by Mistral", { description: "Edit before you send." });
  };

  if (!job)
    return (
      <AppShell>
        <div className="h-96 rounded-3xl glass animate-pulse" />
      </AppShell>
    );

  return (
    <AppShell>
      <Link to="/jobs" className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground mb-6">
        <ArrowLeft className="size-4" /> Back to feed
      </Link>

      <div className="grid md:grid-cols-3 gap-6">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5 }}
          className="md:col-span-2 glass-strong rounded-3xl p-7 md:p-9 relative overflow-hidden"
        >
          <div className="absolute -top-32 -right-20 size-80 rounded-full bg-[var(--gradient-liquid)] opacity-10 blur-3xl pointer-events-none" />
          <div className="flex items-center gap-2 text-xs uppercase tracking-widest text-muted-foreground mb-3">
            <Sparkles className="size-3.5 text-liquid" /> Apply · {job.matchScore}% match
          </div>
          <h1 className="font-display text-3xl md:text-4xl font-bold tracking-tight">{job.title}</h1>
          <p className="text-muted-foreground mt-2">
            {job.startup.name} · <span className="text-muted-foreground/70">{job.startup.stage}</span>
          </p>
          <div className="flex flex-wrap items-center gap-3 mt-3 text-xs text-muted-foreground">
            <span className="inline-flex items-center gap-1"><MapPin className="size-3" />{job.location}</span>
            <span>·</span>
            <span className="capitalize">{job.type}</span>
            <span>·</span>
            <span>${(job.salaryRange.min / 1000).toFixed(0)}–${(job.salaryRange.max / 1000).toFixed(0)}k</span>
          </div>

          <p className="text-sm text-muted-foreground leading-relaxed mt-6">{job.description}</p>

          <div className="mt-5 flex flex-wrap gap-1.5">
            {job.techStack.map((t) => (
              <span key={t} className="text-[11px] px-2.5 py-1 rounded-full bg-muted/50 border border-border text-muted-foreground">
                {t}
              </span>
            ))}
          </div>

          <div className="mt-9">
            <div className="flex items-center justify-between mb-2">
              <label className="text-sm font-medium">Your message</label>
              <button onClick={draftWithAI} className="inline-flex items-center gap-1.5 text-xs text-liquid hover:opacity-80">
                <Wand2 className="size-3.5" /> Draft with AI
              </button>
            </div>
            <textarea
              value={cover}
              onChange={(e) => setCover(e.target.value)}
              rows={9}
              placeholder={`Tell ${job.startup.name} why you're the right hire…`}
              className="w-full bg-background/40 border border-border rounded-2xl p-4 text-sm leading-relaxed focus:outline-none focus:border-foreground/30 resize-none"
            />
            <div className="mt-5 flex items-center justify-between">
              <p className="text-xs text-muted-foreground">Your profile and resume are auto-attached.</p>
              <button
                onClick={() => apply.mutate()}
                disabled={!cover.trim() || apply.isPending}
                className="btn-liquid !px-6 disabled:opacity-50 disabled:pointer-events-none"
              >
                <Send className="size-4" />
                {apply.isPending ? "Submitting…" : "Submit application"}
              </button>
            </div>
          </div>
        </motion.div>

        <motion.aside
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5, delay: 0.1 }}
          className="glass-strong rounded-3xl p-6 h-fit"
        >
          <div className="text-xs uppercase tracking-widest text-muted-foreground mb-4">Why you fit</div>
          <ul className="space-y-3 text-sm">
            {[
              `Stack overlap on ${job.techStack.slice(0, 2).join(" + ")}`,
              `${job.matchScore}% Mistral match score`,
              "Salary band aligned with your target",
              "Response time under 24h on this team",
            ].map((line, i) => (
              <li key={i} className="flex gap-2">
                <span className="mt-1 size-1.5 rounded-full bg-[var(--gradient-liquid)] shrink-0" />
                <span className="text-muted-foreground">{line}</span>
              </li>
            ))}
          </ul>
        </motion.aside>
      </div>
    </AppShell>
  );
}
